### ISSUE TITLE
Add the "CVD Events" dataset

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/shhs-data-dictionary#1060]
We have an "shhs-cvd" dataset already, which is summarized to one record per participant. The "events" dataset is formatted as one record per participant event, e.g. stroke, MI, CABG. These events each have day offsets from the index date and the stroke events are categorized by type of stroke.

**Comment by mcailler** [comment]
The dataset exists currently in `nsrr_prep\releases\0.7.0.pre`; the only variables that need to be created (in the CVD Outcomes folder) are:

- event
  - choices
- stk_type
  - choices
- fstk_type
  - choices
- event_dt
  - numeric; unit: days

CC: @michellereid
