### ISSUE TITLE
Domains for dichotomous CVD outcomes variables should remove "Don't Know" option

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/shhs-data-dictionary#1070]
E.g.

https://www.sleepdata.org/datasets/shhs/variables/any_chd
https://www.sleepdata.org/datasets/shhs/variables/stk_fatal

Check source data and confirm these were only reported in "Yes" and "No" bins by parent cohort. Change domain for these particular variables if so.

**Comment by remomueller** [comment]
Here's an example of one where the source does not have a don't know option:

https://staging.partners.org/sleepdata.org/datasets/shhs/variables/sh317

Here's the form (page 7)
https://staging.partners.org/sleepdata.org/datasets/shhs/variables/sh317/form?name=shhs2_sleep_habits_questionnaire

**Comment by mrueschman** [comment]
Yeahhh, just in random browsing here and there recently I got the impression that the domain with the "Don't Know" choice is mistakenly used in many places. Maybe I can ask Jared or someone to review variables using the "noyes01" domain. There are 269 variables using it.
