### ISSUE TITLE
Add 'ess*' labels to all ESS component variables

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/shhs-data-dictionary#1074]
Will improve search rankings.

**Comment by remomueller** [comment]
Should these be similar to `ess1`, `ess2` to correspond with the position of the question or is going to be a generic `ess` label?

**Comment by mrueschman** [comment]
Yeah -- I was going to tag the question position on the end. Updated title.

**Comment by mrueschman** [comment]
Addressed in b40fe1c5dfad523033ffa392e4eceb5a33568d7d

**Comment by remomueller** [comment]
Deploying these changes to staging to see how it affects the search.

**Comment by remomueller** [comment]
Both https://staging.partners.org/sleepdata.org/datasets/shhs/variables?s=ess4 and https://staging.partners.org/sleepdata.org/datasets/shhs/variables?s=ess are working as expected, thanks!

**Comment by mrueschman** [comment]
I think it's rendering Markdown in the Description box, which is why it makes a numbered list for `sh319d`? Sort of confusing since it's actually Question 4 in the ESS itself. I checked the variable itself and the description actually starts with "19. What is the chance.." because it's question 19 on that particular questionnaire! Confusing!

**Comment by remomueller** [comment]
Yep, I have it render the markdown to handle links in descriptions, for example: https://staging.partners.org/sleepdata.org/datasets/shhs/variables/fuweight

I'll see if I can have it ignore numbered lists as that's what's causing the issue here.

**Comment by mrueschman** [comment]
Closed in b40fe1c
