### ISSUE TITLE
Strange characters in overall_shhs1

### ISSUE THREAD

**Issue by remomueller** [sleepepi/shhs-data-dictionary#1097]
https://github.com/sleepepi/shhs-data-dictionary/blob/master/variables/Measurements/Polysomnography/Signal%20Quality/SHHS1/overall_shhs1.json

**Comment by michellereid** [comment]
Fixed in v0.13.1

**Comment by remomueller** [comment]
850eb826ca68537da0426bc7c893f1fab0bd12dd and 7037b4f0f23aa15daf4a862a71de946d3ca24e52
